### ISSUE TITLE
Compatibility with parallel_tests v4

### ISSUE THREAD

**Issue by franzliedke** [serpapi/turbo_tests#28]
Can we get a new release compatible with [version 4](https://github.com/grosser/parallel_tests/blob/v4.2.0/CHANGELOG.md) of `parallel_tests` which was released last November? 🙏🏼

**Comment by ilyazub** [comment]
Hi @franzliedke,

Which change are you interested in to be ported: https://github.com/grosser/parallel_tests/pull/891 or https://github.com/grosser/parallel_tests/pull/884/?

**Comment by franzliedke** [comment]
Neither, really. It's more about this constraint in the gemspec:

https://github.com/serpapi/turbo_tests/blob/ec37ceebdab2c13587848a5310b754c1dae75473/turbo_tests.gemspec#L23

That's causing GitHub's dependabot to downgrade `turbo_tests` to version 1.0.0 (which doesn't have a version constraint) as part of an upgrade of `parallel_tests` to v4. 😆

**Comment by ilyazub** [comment]
Makes sense :-) Please submit a PR with dependency upgrade. If tests will pass, it should be good to go.
